"""Typed domain contract for soil layer generation."""

from .models import (
    ArtifactKind,
    ArtifactReference,
    BatchStatus,
    CoordinateBounds,
    DEFAULT_PROCESSING_LIMITS,
    DepthRange,
    ErrorCode,
    GeoJsonFeature,
    GeoJsonFeatureCollection,
    GeoJsonMultiPolygon,
    GeoJsonPolygon,
    GridDefinition,
    LayerData,
    FieldLayerResult,
    LayerBatchResult,
    LayerError,
    LayerRequest,
    LayerResult,
    LayerStatistics,
    LegendEntry,
    Parameter,
    ProcessingLimits,
    ResultStatus,
    Source,
)

__all__ = [
    "ArtifactKind",
    "ArtifactReference",
    "BatchStatus",
    "CoordinateBounds",
    "DEFAULT_PROCESSING_LIMITS",
    "DepthRange",
    "ErrorCode",
    "GeoJsonFeature",
    "GeoJsonFeatureCollection",
    "GeoJsonMultiPolygon",
    "GeoJsonPolygon",
    "GridDefinition",
    "LayerData",
    "FieldLayerResult",
    "LayerBatchResult",
    "LayerError",
    "LayerRequest",
    "LayerResult",
    "LayerStatistics",
    "LegendEntry",
    "Parameter",
    "ProcessingLimits",
    "ResultStatus",
    "Source",
]
